"""Build manifests/resource_manifest.csv and docs/RESOURCES.md from the live source registry plus the non-registry resources.
    PYTHONPATH=src python scripts/build_resource_manifest.py
Status columns come from the registry (verified or not), never from this file."""
import csv
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CATS = ["already available", "generated by preparer", "publicly downloadable", "requires account", "requires approval/request",
        "requires human scientific sign-off", "unavailable / scientifically unsuitable"]
COLS = ["resource", "category", "purpose", "source", "url_or_doi_status", "access_requirement", "licence_requirement", "required_files",
        "repository_destination", "dependent_experiments", "current_status", "acquisition_action", "verification_action", "next_step"]

DATA = {  # registry id -> (category, access, files, destination, experiments, acquisition, next)
 "S15": ("publicly downloadable", "Mendeley Data (open; free login only if asked)", "all dataset files", "data/raw/hupa_ucm/", "M6, M4, M1", "docs/data/01_hupa_ucm.md", "docs/data/04_ingestion_and_mapping.md"),
 "S17": ("publicly downloadable", "Bristol data repository, Open part only", "BrisT1D-Open files", "data/raw/brist1d/", "M6, M4, M1", "docs/data/02_bristol_brist1d.md", "docs/data/04_ingestion_and_mapping.md"),
 "S16": ("requires approval/request", "Synapse account + access requirement approval", "54 .xlsx files", "data/raw/diatrend/ (git-ignored)", "L4, M5", "docs/data/03_diatrend.md", "docs/data/04_ingestion_and_mapping.md"),
 "S18": ("requires approval/request", "Data use agreement with the custodians", "OhioT1DM release files", "data/raw/ohiot1dm/ (git-ignored)", "optional method check", "docs/data/06_ohiot1dm.md", "docs/data/04_ingestion_and_mapping.md"),
 "S19": ("requires approval/request", "Vivli request, per-member DUA, secure environment", "T1DEXI study data (inside Vivli)", "NOT in the repository (analysis inside Vivli)", "M2, M3 (only if cycle variables exist)", "docs/data/05_t1dexi.md", "docs/data/04_ingestion_and_mapping.md"),
 "S27": ("requires account", "Copernicus CDS account + licence acceptance (to confirm)", "pre-registered locations/period", "data/raw/climate/era5_land/", "E1, E2, scenario S5", "docs/data/07_climate_and_context.md", "freeze location rule first; E1/E2 production reader needed (D-12)"),
 "S28": ("requires account", "Copernicus CDS account (to confirm)", "same", "data/raw/climate/era5/", "E1", "docs/data/07_climate_and_context.md", "same"),
 "S29": ("publicly downloadable", "public API (to confirm)", "same", "data/raw/climate/nasa_power/", "E1", "docs/data/07_climate_and_context.md", "same"),
 "S30": ("requires account", "IMD portal; registration/terms to be confirmed", "gridded temperature", "data/raw/climate/imd/", "E1", "docs/data/07_climate_and_context.md", "same"),
 "S31": ("publicly downloadable", "public release (to confirm)", "database II files", "data/raw/comfort/", "E2", "docs/data/07_climate_and_context.md", "same"),
}


def main() -> None:
    reg = list(csv.DictReader(open(ROOT / "data/sources_registry.csv", encoding="utf-8-sig")))
    rows = []
    for r in reg:
        sid = r["source_id"]
        verified = bool(r["access_date"].strip() and r["licence"].strip() and r["verified_by"].strip())
        status = "verified" if verified else "UNVERIFIED (no access date / licence / sign-off)"
        if sid in DATA:
            cat, acc, files, dest, exps, acq, nxt = DATA[sid]
            rows.append(dict(resource=f"{sid} {r['title'][:70]}", category=cat, purpose=r["used_for"], source=r["citation_or_url"][:90],
                             url_or_doi_status="DOI/URL present in registry; not opened by the preparer", access_requirement=acc,
                             licence_requirement="read the licence on the provider page and record it verbatim", required_files=files,
                             repository_destination=dest, dependent_experiments=exps, current_status=status, acquisition_action=acq,
                             verification_action="source_verification worksheet row + register_raw digest", next_step=nxt))
        else:
            rows.append(dict(resource=f"{sid} {r['title'][:70]}", category="requires human scientific sign-off", purpose=r["used_for"],
                             source=r["citation_or_url"][:90], url_or_doi_status="DOI/URL in registry" if "doi" in r["citation_or_url"].lower() or "http" in r["citation_or_url"] else "citation only: locate the exact record",
                             access_requirement="journal/provider page (open or institutional)", licence_requirement="cite only; record copyright line",
                             required_files="the paper/page itself (evidence page/table recorded in the worksheet)", repository_destination="docs/literature/ worksheets, literature/*.csv",
                             dependent_experiments="see registry used_for", current_status=status, acquisition_action="open the source",
                             verification_action="docs/literature/01_source_verification_runbook.md", next_step="docs/START_HERE.md steps 2-4"))
    extra = [
     ("Repository code and tests", "already available", "all experiments", "uploaded tarball", "n/a", "none", "MIT (LICENSE)", "repository", "repo root", "all", "present; tests pass", "git init + commit + tag before production runs", "python -m pytest tests -q", "docs/runbook/02_environment_setup.md"),
     ("Project document (docx)", "already available", "scientific definition", "uploaded", "n/a", "none", "n/a", "docx", "outside repo", "all", "present", "none", "claims_lint on any text derived from it", "docs/START_HERE.md"),
     ("Execution package (these documents, matrix, worksheets, notebook, tools)", "generated by preparer", "execution", "this repository", "n/a", "none", "MIT", "docs/, scripts/, notebooks/, templates/, manifests/", "repo", "all", "generated 2026-10-07", "none", "run the tests, regenerate matrix with `make readiness`", "docs/START_HERE.md"),
     ("GitHub account + repository", "requires account", "canonical online repository, CI, Pages, Releases", "github.com", "n/a", "free account", "choose MIT (already in LICENSE)", "whole repository (without data)", "GitHub", "release", "to create", "docs/release/release_checklist.md section A", "push; CI green", "docs/release/release_checklist.md"),
     ("Kaggle account (optional)", "requires account", "independent repeat run", "kaggle.com", "n/a", "free account + phone verification for Internet", "per dataset licence", "open datasets only", "Kaggle", "M4, M1, M6", "optional", "docs/ml/kaggle_and_ml_guide.md", "verify_run_dir.py on imported runs", "docs/ml/kaggle_and_ml_guide.md"),
     ("Synapse account", "requires account", "DiaTrend access", "synapse.org", "n/a", "free account", "per access requirement", "n/a", "n/a", "L4, M5", "to create", "docs/data/03_diatrend.md", "n/a", "docs/data/03_diatrend.md"),
     ("Vivli account", "requires approval/request", "T1DEXI access", "vivli.org", "n/a", "account + institution signatory", "DUA", "n/a", "n/a", "M2, M3", "to create", "docs/data/05_t1dexi.md", "n/a", "docs/data/05_t1dexi.md"),
     ("Owner decisions: pre-registration freeze", "requires human scientific sign-off", "confirmatory criteria", "docs/prereg/conclusions.yaml", "n/a", "owner", "n/a", "conclusions.yaml", "docs/prereg/", "F5 and all confirmatory claims", "frozen: false", "docs/prereg/freeze_procedure.md", "git tag prereg-v1", "docs/START_HERE.md step 7"),
     ("E1/E2 production reader (code)", "unavailable / scientifically unsuitable", "climate branch", "to be written after the location rule is frozen and one real file is seen", "n/a", "n/a", "n/a", "n/a", "src/iris/thermal/", "E1, E2, scenario S5", "NOT IMPLEMENTED (code limitation)", "see docs/data/07_climate_and_context.md", "tests on real file", "decision D-12"),
     ("BrisT1D-Restricted part", "unavailable / scientifically unsuitable", "not needed", "Bristol repository (restricted)", "n/a", "approval", "restricted", "n/a", "n/a", "none", "out of scope", "none", "none", "none"),
     ("Kaggle competition version of BrisT1D", "unavailable / scientifically unsuitable", "different lagged wide layout", "Kaggle", "n/a", "competition rules", "competition terms", "n/a", "n/a", "none", "do not mix with repository files", "none", "none", "none"),
     ("Cycle labels for HUPA-UCM, BrisT1D, DiaTrend", "unavailable / scientifically unsuitable", "do not exist; must not be inferred", "n/a", "n/a", "n/a", "n/a", "n/a", "n/a", "M2, M3", "scientifically unjustified", "none", "none", "T1DEXI route (docs/data/05_t1dexi.md)"),
    ]
    for e in extra:
        rows.append(dict(zip(COLS, e)))
    (ROOT / "manifests").mkdir(exist_ok=True)
    with open(ROOT / "manifests/resource_manifest.csv", "w", newline="", encoding="utf-8") as fh:
        w = csv.DictWriter(fh, fieldnames=COLS); w.writeheader(); w.writerows(rows)
    md = ["# Resources needed to finish IRIS", "", "Generated by `scripts/build_resource_manifest.py` from `data/sources_registry.csv` (status column is read from the registry, not asserted here). "
          "Full machine-readable table: `manifests/resource_manifest.csv`.", ""]
    for c in CATS:
        sel = [r for r in rows if r["category"] == c]
        if not sel:
            continue
        md += [f"## {c} ({len(sel)})", "", "| Resource | Needed for | Status | Where it goes | Do this | Then |", "|---|---|---|---|---|---|"]
        for r in sel:
            md.append(f"| {r['resource']} | {r['dependent_experiments'] or r['purpose']} | {r['current_status']} | {r['repository_destination']} | {r['acquisition_action']} | {r['next_step']} |".replace("\n", " "))
        md.append("")
    (ROOT / "docs/RESOURCES.md").write_text("\n".join(md), encoding="utf-8")
    print(len(rows), "resources")


if __name__ == "__main__":
    main()
